M48
; DRILL file {KiCad 9.0.7} date 2026-01-23T22:21:49+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-23T22:21:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.950
%
G90
G05
T1
X76.0Y-70.5
T2
X80.0Y-72.8
X82.5Y-72.8
X85.0Y-72.8
X87.5Y-72.8
M30
